config/routes.rb
Rails.application.routes.draw do
  resources :technologies

  resources :companies

  root 'root#index'
  
  get 'search', to:'search#index'
  post 'search', to:'search#search'

end

app/models/companies_technology.rb
class CompaniesTechnology < ActiveRecord::Base
  belongs_to :company
  belongs_to :technology
end

app/models/company.rb
class Company < ActiveRecord::Base
  has_and_belongs_to_many :technologies


end

app/models/technology.rb
class Technology < ActiveRecord::Base
  has_and_belongs_to_many :companies

  scope :top, -> { order(:companies.count, desc)}

  def companies_count
    self.companies.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    return nil if session[:user_id].nil?
    User.find(session[:user_id])
  end
  
  def search_by_companies
    map = Company.all.map do |company|
      {tolower(company.name) => company}
    end
  end
  
  def self.search_by_companies(param)
    param = param.downcase
    map = Hash[Company.all.map{|com| [com.name.downcase, com]}]
    result = []
    map.keys.each do |key|
      result << map[key] if key.include? param
    end
    result
  end
  
  def self.search_by_technologies(param)
    param = param.downcase
    map = Hash[Technology.all.map{|tech| [tech.name.downcase, tech]}]
    result = []
    map.keys.each do |key|
      result << map[key] if key.include? param
    end
    result
  end
  
  def self.top_technologies(n)
    Technology.all.sort_by{ |t| t.companies.count }.reverse.take(n)
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]
  before_action :set_companies_and_technologies, only: [:index, :show]


  # GET /companies
  # GET /companies.json
  def index
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @technology = Technology.new

  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)
    company_technologies.each { |t| @company.technologies << Technology.find(t[1]) }

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        company_technologies.each { |t| @company.technologies << Technology.find(t[1]) if not @company.technologies.include? Technology.find(t[1]) }
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :logo, :description, :admin_edited)
    end

    def company_technologies
      params.require(:company).permit(:technologies)
    end

    def set_companies_and_technologies
      @technologies = Technology.all
      @companies = Company.all
    end

end

app/controllers/load_techs.rb
class LoadTechs
  def self.read_json_techs(url)
    response = HTTParty.get(url)
    json = JSON.parse(response.body)
  end

  def self.lue_json
    url = "https://raw.githubusercontent.com/ElbertF/Wappalyzer/master/share/apps.json"
    haku = read_json_techs(url)
    haku["apps"].each do |k|
      Technology.create name:k[0], url:k[1]["website"]
      Thread.sleep(10)
    end
  end
end

app/controllers/root_controller.rb
class RootController < ApplicationController
  before_action :set_companies_and_technologies, only: [:index, :show]

  # GET /companies
  # GET /companies.json
  def index
    @top_tech = @technologies.sort_by {|t| t.companies.count}.reverse

  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  private

  def company_technologies
    params.require(:company).permit(:technologies)
  end

  def set_companies_and_technologies
    @technologies = Technology.all
    @companies = Company.all
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @companies = []
    @technologies = []
  end
  
  def search
    @companies = ApplicationController.search_by_companies(params[:search])
    @technologies = ApplicationController.search_by_technologies(params[:search])
    render :index
  end
end

app/controllers/technologies_controller.rb
class TechnologiesController < ApplicationController
  before_action :set_technology, only: [:show, :edit, :update, :destroy]

  # GET /technologies
  # GET /technologies.json
  def index
    @technologies = Technology.all
  end

  # GET /technologies/1
  # GET /technologies/1.json
  def show
  end

  # GET /technologies/new
  def new
    @technology = Technology.new
  end

  # GET /technologies/1/edit
  def edit
  end

  # POST /technologies
  # POST /technologies.json
  def create
    @technology = Technology.new(technology_params)

    respond_to do |format|
      if @technology.save
        format.html { redirect_to @technology, notice: 'Technology was successfully created.' }
        format.json { render :show, status: :created, location: @technology }
      else
        format.html { render :new }
        format.json { render json: @technology.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /technologies/1
  # PATCH/PUT /technologies/1.json
  def update
    respond_to do |format|
      if @technology.update(technology_params)
        format.html { redirect_to @technology, notice: 'Technology was successfully updated.' }
        format.json { render :show, status: :ok, location: @technology }
      else
        format.html { render :edit }
        format.json { render json: @technology.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /technologies/1
  # DELETE /technologies/1.json
  def destroy
    @technology.destroy
    respond_to do |format|
      format.html { redirect_to technologies_url, notice: 'Technology was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_technology
      @technology = Technology.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def technology_params
      params.require(:technology).permit(:name, :url, :logo, :front, :back, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/root_helper.rb
module RootHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/technologies_helper.rb
module TechnologiesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
    <% if @company.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

          <ul>
            <% @company.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :logo %><br>
      <%= f.text_field :logo %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </div>
    <div class="field">
      <%= f.label :admin_edited %><br>
      <%= f.check_box :admin_edited %>
    </div>
    <div class="field">
      <%= f.label :technologies %>
      <%= f.select :technologies, options_from_collection_for_select(Technology.all, :id, :name) %>
    </div>
    <div class="actions">
      <%= f.submit class:"btn btn-primary"%>
    </div>
<% end %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<h1>Listing Companies</h1>

<h3>Filter by technology</h3>
<div class="btn-group" role="group" aria-label="...">
  <% ApplicationController.top_technologies(20).each do |tech| %>
    <button type="button"><%= tech.name %></button>
  <% end %>
</div>

<table class="table table-striped">
  <thead>
    <tr><h4>
      <th width="40%"><span class="glyphicon glyphicon-th-list"></span> Name</th>
      <th width="10%"><span class="glyphicon glyphicon-eye-open"></span> Logo</th>
      <th width="15%"><span class="glyphicon glyphicon-new-window"></span> Description</th>
      <th colspan="35%"><span class="glyphicon glyphicon-stats"></span> Technologies</th>
    </h4></tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
     <% unless company.name.empty? || company.technologies.empty? || company.logo == "tyhjä" %>
      <tr>
        <td><%= link_to company.name.capitalize, company %></td>
        <% unless company.logo == "tyhjä" %>
          <td><%= image_tag(company.logo, :height => '32', :width => '32') %></td>
        <% else %>
          <td><%= image_tag('noav.png', :height => '32', :width => '32') %></td>
        <% end %>

        <td><button type="button" class="btn btn-info btn-sm" data-toggle="popover" title="<%= company.name.capitalize %>" data-animation="true" data-trigger="hover click" data-content="<%= company.description %>">Info</button></td>
        <td>
          <ul class="list-inline">
            <% company.technologies.each do |tech| %>
              <li>
                <a href="http://<%= tech.url %>" target="_blank">
                  <img src="<%= tech.logo %>" height="32px">
                </a>
              </li>
            <% end %>
          </ul>
        </td>
  <% if not current_user.nil? %>        
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <% end %>    
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<% if not current_user.nil? %>  
  <%= link_to 'New Company', new_company_path %>
<% end %>

app/views/companies/new.html.erb
<h2>Scan website</h2>

<%= form_for(@company) do |f| %>
    <% if @company.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

          <ul>
            <% @company.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :url %><br>
      <%= f.text_field :url %>
    </div>

    <div class="actions">
      <%= f.submit "New website", class:"btn btn-primary"%>
    </div>
<% end %>


<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company.name %>
  <%= image_tag(@company.logo, :height => '64', :width => '64', :align => 'left') %>
</p>

<p>
  <strong>Description:</strong>
  <%= @company.description %>
</p>

<p>
  <strong>Admin edited:</strong>
  <%= @company.admin_edited %>
</p>

<p>
  <strong>Technologies:</strong>
</p>

<p>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Logo</th>
    </tr>
  </thead>

  <tbody>
    <% @company.technologies.each do |t| %>
      <tr>
        <td><%= link_to t.name, t %></td>
        <td><img src="<%= t.logo %>" height="32px" width="32px"></td>
      </tr>
    <% end %>
  </tbody>
</table>
</p>


<% if not current_user.nil? %>  
  <%= form_for(@company) do |f| %>
    <%= f.text_field :description %>
    <%= f.submit 'Update description', :size => 80, class:"btn btn-primary btn-xs" %>
  <% end %>

<%= form_for(@technology) do |f| %>
  <div class="field">
    <%= f.label :technologies %>
    <%= f.select :id, options_from_collection_for_select(@technologies, :id, :name) %>
    <%= f.submit class:"btn btn-primary btn-xs" %>
  </div>
<% end %>

<%= link_to 'Edit', edit_company_path(@company) %> |
<% end %>
<%= link_to 'Back', companies_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- link_to 'Home', root_path, class: 'navbar-brand' -->
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
<<div class="input-group nav navbar-nav navbar-right" role="group">
  <%= form_tag search_path do %>
    <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "search..." %>
  <span class="input-group-btn">
    <%= submit_tag "Search", class: "btn btn-default" %>
  </span> 
  <% end %> 
</div>
    </div>

  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<div class="btn-group" role="group" aria-label="...">
  <%= link_to "Home", root_path, class:"btn btn-warning" %>
  <%= link_to Company, companies_path, class:"btn btn-default" %>
  <%= link_to Technology, technologies_path, class:"btn btn-default"  %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Solinor Hackathon2015" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Solinor Hackathon2015" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
<script type="text/javascript">
$(document).ready(function(){
    $('[data-toggle="popover"]').popover({
        placement : 'right'
    });
});

</script>   
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>

      <div class="row">
        <div class="col-md-10 col-md-offset-1">
          <%= yield %>
        </div>
      </div>

    </main>
  </body>
</html>

app/views/search/index.html.erb
<h1>Listing Companies</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Logo</th>
      <th>Description</th>
      <th>Admin edited</th>
      <th>Technologies</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= link_to company.name, company %></td>
        <% unless company.logo == "tyhjä" %>
          <td><%= image_tag(company.logo, :height => '32', :width => '32') %></td>
        <% else %>
          <td><%= image_tag('noav.png', :height => '32', :width => '32') %></td>
        <% end %>
        <td><%= company.description %></td>
        <td><%= company.admin_edited %></td>
        <td>
          <ul class="list-inline">
            <% company.technologies.each do |tech| %>
              <li>
                <a href="<%= technology_path(tech) %>" target="_blank">
                  <img src="<%= tech.logo %>">
                </a>
              </li>
            <% end %>
          </ul>
        </td>
  <% if not current_user.nil? %>        
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  <% end %>    
      </tr>
    <% end %>
  </tbody>
</table>

<h1>Listing Technologies</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Logo</th>
      <th>Front</th>
      <th>Back</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @technologies.each do |technology| %>
      <tr>
        <td><%= link_to technology.name, technology %></td>
        <td><%= link_to technology.url, "http://#{technology.url}" %></td>
        <td><img src="<%= technology.logo %>"></td>
        <td><%= technology.front %></td>
        <td><%= technology.back %></td>
        <td><%= technology.description %></td>
<% if not current_user.nil? %>          
        <td><%= link_to 'Edit', edit_technology_path(technology) %></td>
        <td><%= link_to 'Destroy', technology, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/technologies/_form.html.erb
<%= form_for(@technology) do |f| %>
    <% if @technology.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@technology.errors.count, "error") %> prohibited this technology from being saved:</h2>

          <ul>
            <% @technology.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :url %><br>
      <%= f.text_field :url %>
    </div>
    <div class="field">
      <%= f.label :logo %><br>
      <%= f.text_field :logo %>
    </div>
    <div class="field">
      <%= f.label :front %><br>
      <%= f.check_box :front %>
    </div>
    <div class="field">
      <%= f.label :back %><br>
      <%= f.check_box :back %>
    </div>
    <div class="field">
      <%= f.label :description %><br>
      <%= f.text_area :description %>
    </div>
    <div class="actions">
      <%= f.submit class:"btn btn-primary" %>
    </div>
    
<% end %>

app/views/technologies/edit.html.erb
<h1>Editing Technology</h1>

<%= render 'form' %>

<%= link_to 'Show', @technology %> |
<%= link_to 'Back', technologies_path %>

app/views/technologies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Technologies</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Url</th>
      <th>Logo</th>
      <th>Front</th>
      <th>Back</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @technologies.each do |technology| %>
      <tr>
        <td><%= link_to technology.name, technology %></td>
        <td><%= link_to technology.url, "http://#{technology.url}" %></td>
        <td><img src="<%= technology.logo %>"></td>
        <td><%= technology.front %></td>
        <td><%= technology.back %></td>
        <td><%= technology.description %></td>
<% if not current_user.nil? %>          
        <td><%= link_to 'Edit', edit_technology_path(technology) %></td>
        <td><%= link_to 'Destroy', technology, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if not current_user.nil? %>  
  <%= link_to 'New Technology', new_technology_path %>
<% end %>

app/views/technologies/new.html.erb
<h1>New Technology</h1>

<%= render 'form' %>

<%= link_to 'Back', technologies_path %>

app/views/technologies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @technology.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @technology.url %>
</p>

<p>
  <strong>Logo:</strong>
  <%= @technology.logo %>
</p>

<p>
  <strong>Front:</strong>
  <%= @technology.front %>
</p>

<p>
  <strong>Back:</strong>
  <%= @technology.back %>
</p>

<p>
  <strong>Description:</strong>
  <%= @technology.description %>
</p>

<br>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Logo</th>
    </tr>
  </thead>

  <tbody>
    <% @technology.companies.each do |c| %>
      <tr>
        <td><%= link_to c.name, c %></td>
        <td><img src="<%= c.logo %>" height="32px" width="32px"></td>
      </tr>
    <% end %>
  </tbody>
</table>



<% if not current_user.nil? %>  
<%= link_to 'Edit', edit_technology_path(@technology) %> |
<% end %>
<%= link_to 'Back', technologies_path %>